# Generated by Django 4.0.5 on 2022-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultdata',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('consultCategory', models.CharField(default='', max_length=4)),
                ('consultTitle', models.CharField(default='', max_length=50)),
                ('consultName', models.CharField(default='', max_length=50)),
                ('consultDate', models.CharField(default='', max_length=50)),
                ('consultId', models.CharField(default='', max_length=50)),
                ('consultDepartment', models.CharField(default='', max_length=50)),
                ('consultState', models.CharField(default='', max_length=50)),
                ('consultContent', models.TextField(blank=True, default='')),
                ('answerDepartment', models.CharField(default='', max_length=50)),
                ('answerDate', models.CharField(default='', max_length=50)),
                ('answerContent', models.TextField(blank=True, default='')),
            ],
        ),
    ]
